"""Central security harness for sacremoses.

This file records the WHOLE audited candidate set, not only the exploitable
ones. Every payload that was considered is kept here -- including the ones that
measured benign -- so that a future change which makes one of them exploitable
fails a test instead of shipping.

Sections:

1. ReDoS (CWE-1333). The library had a real one: ``has_numeric_only`` was
   ``re.search(r"(.*)[\\s]+(\\#NUMERIC_ONLY\\#)", text)``, where the leading
   ``(.*)`` made an all-whitespace payload backtrack catastrophically (patched
   in 8ad457e; see also test_no_redos_has_numeric_only.py). The remaining
   regexes with a nested-quantifier *shape* are exercised here too: they
   measured linear because their inner groups are delimiter-anchored, but the
   shape is the dangerous one, so the measurement is pinned.

2. Data-as-code. sacremoses reads no data files at run time: the Unicode
   character classes and nonbreaking prefixes are Python modules generated by
   ``tools/generate_data_modules.py``. That removes the run-time filesystem
   dependency and, with it, the path built by interpolating a caller-supplied
   category/language into a filename.

Timings are deliberately generous so the suite is not flaky on a loaded CI box;
the payloads are sized so that a genuine blow-up cannot finish inside them.
"""

import re
import time
import unittest

from sacremoses.corpus import NonbreakingPrefixes, Perluniprops
from sacremoses.normalize import MosesPunctNormalizer
from sacremoses.tokenize import MosesDetokenizer, MosesTokenizer
from sacremoses.truecase import MosesDetruecaser

#: Ceiling for a single hostile payload. A catastrophic backtrack on these
#: inputs runs for minutes, so this separates "linear" from "exploitable"
#: without being tight enough to flake.
BUDGET_SECONDS = 20


#: Timing repetitions. One sample is not a measurement: on a loaded CI runner a
#: single timing can be several times the true cost, and timing these payloads
#: once gave a 40% flake rate (2 failures in 5 consecutive runs). Contention can
#: only ever ADD time, so the fastest of several runs is the closest to the
#: truth. Long calls are measured once -- they are already long enough that
#: scheduler noise is a small fraction, and repeating would multiply the cost of
#: a test that exists to prove something is *not* slow.
TIMING_REPEATS = 3
CHEAP_ENOUGH_TO_REPEAT = 0.5


def elapsed(func, *args, **kwargs):
    best = None
    for _ in range(TIMING_REPEATS):
        start = time.perf_counter()
        func(*args, **kwargs)
        seconds = time.perf_counter() - start
        best = seconds if best is None else min(best, seconds)
        if seconds > CHEAP_ENOUGH_TO_REPEAT:
            break
    return best


class ReDoSPayloads(unittest.TestCase):
    """Hostile inputs driven through the public API."""

    def test_whitespace_flood_through_tokenizer(self):
        # The shape of the original CVE: a long run of whitespace that never
        # reaches the literal the pattern requires.
        moses = MosesTokenizer()
        self.assertLess(elapsed(moses.tokenize, " " * 20000), BUDGET_SECONDS)

    def test_numeric_only_marker_flood(self):
        moses = MosesTokenizer()
        self.assertLess(
            elapsed(moses.has_numeric_only, " " * 50000 + "x"), BUDGET_SECONDS
        )

    def test_punctuation_flood_through_tokenizer(self):
        moses = MosesTokenizer()
        for payload in ("." * 20000, "-" * 20000, "'" * 20000, '"' * 20000):
            self.assertLess(elapsed(moses.tokenize, payload), BUDGET_SECONDS)

    def test_flood_through_normalizer(self):
        normalizer = MosesPunctNormalizer()
        for payload in (" " * 50000, "(" * 20000, '"' * 20000, "“" * 20000):
            self.assertLess(elapsed(normalizer.normalize, payload), BUDGET_SECONDS)

    def test_flood_through_detokenizer(self):
        detok = MosesDetokenizer()
        for tokens in (["("] * 5000, ["'"] * 5000, ["."] * 5000):
            self.assertLess(elapsed(detok.detokenize, tokens), BUDGET_SECONDS)

    def test_long_token_no_whitespace(self):
        # A single unbroken token defeats any per-token bail-out.
        moses = MosesTokenizer()
        self.assertLess(elapsed(moses.tokenize, "a" * 50000), BUDGET_SECONDS)


class ProtectedPatternPayloads(unittest.TestCase):
    """The four BASIC_PROTECTED_PATTERNS carry nested-quantifier shapes.

    They measured LINEAR because each inner group is anchored by a delimiter the
    inner class cannot cross (``\\w+`` cannot span ``.``, ``/`` or ``"``), so the
    engine has only one way to partition the input. The shape is still the
    classic catastrophic one, so these are pinned: if a future edit relaxes an
    inner class, the payload below becomes exponential and this test fails.
    """

    PAYLOADS = {
        # ([\w\-\_]+\.)+ then requires [a-zA-Z]{2,}: a digit denies the tail.
        "BASIC_PROTECTED_PATTERN_4": lambda n: "a@" + "a." * n + "1",
        # (\/\w+)* then requires \/[\w\-\.]+ : a bare trailing slash denies it.
        "BASIC_PROTECTED_PATTERN_5": lambda n: "http://a" + "/a" * n + "/",
        # ( [a-zA-Z0-9]+="?[^"]")+ then requires ' ?/?>' : no '>' denies it.
        "BASIC_PROTECTED_PATTERN_2": lambda n: "<a" + ' a="b"' * n + " ",
        "BASIC_PROTECTED_PATTERN_3": lambda n: "<a" + " a='b'" * n + " ",
    }

    def test_each_pattern_is_not_exponential(self):
        for name, make in self.PAYLOADS.items():
            pattern = re.compile(getattr(MosesTokenizer, name), re.IGNORECASE)
            with self.subTest(pattern=name):
                self.assertLess(elapsed(pattern.search, make(40)), BUDGET_SECONDS)

    def test_protected_patterns_through_public_tokenize(self):
        # How a user actually reaches them: `-p :basic:` on the CLI maps to this.
        moses = MosesTokenizer()
        for name, make in self.PAYLOADS.items():
            with self.subTest(pattern=name):
                self.assertLess(
                    elapsed(
                        moses.tokenize,
                        make(40),
                        protected_patterns=MosesTokenizer.BASIC_PROTECTED_PATTERNS,
                    ),
                    BUDGET_SECONDS,
                )


class NoRuntimeFileLoading(unittest.TestCase):
    """The package must not read data files at run time."""

    def test_corpus_module_opens_no_files(self):
        import sacremoses.corpus as corpus

        source = open(corpus.__file__, encoding="utf-8").read()
        for forbidden in ("open(", "pkgutil", "__file__", "os.path"):
            self.assertNotIn(forbidden, source)

    def test_character_classes_come_from_code(self):
        from sacremoses._data_perluniprops import PERLUNIPROPS

        self.assertGreater(len(PERLUNIPROPS), 20)
        self.assertEqual(
            "".join(Perluniprops().chars("Open_Punctuation")),
            PERLUNIPROPS["Open_Punctuation"],
        )

    def test_prefixes_come_from_code(self):
        from sacremoses._data_nonbreaking_prefixes import NONBREAKING_PREFIXES

        self.assertIn("nonbreaking_prefix.en", NONBREAKING_PREFIXES)
        self.assertEqual(
            list(NonbreakingPrefixes().words("en"))[:4], ["A", "B", "C", "D"]
        )


class TraversalViaDataLookup(unittest.TestCase):
    """A caller-supplied category/language must never reach the filesystem.

    Both lookups used to interpolate their argument into a path
    (``data/perluniprops/<category>.txt``), so a traversing argument was a file
    read. They are dictionary lookups now.
    """

    TRAVERSALS = [
        "../../../../etc/passwd",
        "../../setup",
        "..%2f..%2fetc%2fpasswd",
        "/etc/passwd",
        "Open_Punctuation/../../../etc/passwd",
    ]

    def test_perluniprops_category_cannot_traverse(self):
        perluniprops = Perluniprops()
        for payload in self.TRAVERSALS:
            with self.subTest(payload=payload):
                with self.assertRaises(KeyError):
                    list(perluniprops.chars(payload))

    def test_nonbreaking_language_cannot_traverse(self):
        prefixes = NonbreakingPrefixes()
        english = list(prefixes.words("en"))
        for payload in self.TRAVERSALS:
            with self.subTest(payload=payload):
                # An unknown language falls back to English, as it always has --
                # the point is that it never reads the named file.
                self.assertEqual(list(prefixes.words(payload)), english)


class QuadraticBlowups(unittest.TestCase):
    """Two O(n**2) paths that a hostile input reaches through ``tokenize``.

    Neither is catastrophic backtracking, so a nested-quantifier scan misses
    both -- they are ordinary algorithmic-complexity DoS (CWE-407). Each is
    pinned with a doubling curve rather than a single timing, because a wall
    clock alone cannot tell "slow box" from "quadratic".
    """

    #: Doubling the input may not more than triple the time. Linear is ~2x;
    #: quadratic is ~4x. Three sits between them with room for CI noise.
    MAX_GROWTH = 3.0

    def growth(self, func, make_payload, small, large):
        # Warm the regex cache so the first call does not pay for compilation.
        func(make_payload(small))
        base = elapsed(func, make_payload(small))
        big = elapsed(func, make_payload(large))
        # Floor the denominator: at microsecond scale the ratio is timer noise.
        return big / max(base, 1e-4)

    def test_multidot_run_is_linear(self):
        # ``replace_multidots`` peeled one dot per iteration and re-scanned the
        # whole string each time. '.'*16000 took 16.8s; '.'*64000 several
        # minutes. Both directions are now single-pass.
        moses = MosesTokenizer()
        self.assertLess(
            self.growth(moses.tokenize, lambda n: "." * n, 8000, 16000),
            self.MAX_GROWTH,
        )
        self.assertLess(elapsed(moses.tokenize, "." * 64000), BUDGET_SECONDS)

    #: Exact outputs of the original two-loop implementation, captured before
    #: it was rewritten. ``replace_multidots`` inserts spaces on purpose -- the
    #: marker has to survive as its own token -- so the round trip is not the
    #: identity; what must hold is that every dot run comes back at its own
    #: length and position.
    MULTIDOT_CASES = {
        "": "",
        ".": ".",
        "..": " DOTDOTMULTI",
        "...": " DOTDOTDOTMULTI",
        "a...b": "a DOTDOTDOTMULTI b",
        "..a..": " DOTDOTMULTI a DOTDOTMULTI",
        "x....y...z": "x DOTDOTDOTDOTMULTI y DOTDOTDOTMULTI z",
        "... ...": " DOTDOTDOTMULTI   DOTDOTDOTMULTI",
    }

    def test_multidot_replacement_matches_original(self):
        moses = MosesTokenizer()
        for text, expected in self.MULTIDOT_CASES.items():
            with self.subTest(text=text):
                self.assertEqual(moses.replace_multidots(text), expected)

    def test_multidot_restore_recovers_every_dot(self):
        moses = MosesTokenizer()
        for text in self.MULTIDOT_CASES:
            with self.subTest(text=text):
                restored = moses.restore_multidots(moses.replace_multidots(text))
                # Spaces are introduced deliberately; the dots must be exact.
                self.assertEqual(restored.replace(" ", ""), text.replace(" ", ""))
                self.assertNotIn("MULTI", restored)

    def test_numeric_only_marker_is_linear(self):
        # ``[\s]+`` before a literal made every start position rescan the whole
        # whitespace run: 50k spaces took 96.5s. This is the same regex the
        # 2021 ReDoS fix trimmed a leading ``(.*)`` from -- the quadratic tail
        # survived that patch, so it is pinned separately here.
        moses = MosesTokenizer()
        self.assertLess(
            self.growth(
                moses.has_numeric_only, lambda n: " " * n + "x", 50000, 100000
            ),
            self.MAX_GROWTH,
        )

    def test_custom_prefix_file_loads_linearly(self):
        # `line not in self.NONBREAKING_PREFIXES` scanned a growing list per
        # line. This is the one input path where a caller hands the library a
        # whole file, so its size is entirely under their control: 8k prefixes
        # took ~1s and 64k would have taken a minute.
        import os
        import tempfile

        def load(size):
            handle, path = tempfile.mkstemp(suffix=".txt")
            os.write(handle, "\n".join("Pre%d" % i for i in range(size)).encode())
            os.close(handle)
            try:
                MosesTokenizer(lang="en", custom_nonbreaking_prefixes_file=path)
            finally:
                os.unlink(path)

        self.assertLess(self.growth(load, lambda n: n, 4000, 8000), self.MAX_GROWTH)
        self.assertLess(elapsed(load, 64000), BUDGET_SECONDS)

    def test_custom_prefix_file_semantics_unchanged(self):
        import os
        import tempfile

        handle, path = tempfile.mkstemp(suffix=".txt")
        os.write(
            handle,
            "\n".join(["# comment", "Dr", "Mr", "Dr", "", "  Prof  ", "Mr"]).encode(),
        )
        os.close(handle)
        try:
            moses = MosesTokenizer(lang="en", custom_nonbreaking_prefixes_file=path)
        finally:
            os.unlink(path)
        # Order preserved, first occurrence kept, comments and blanks skipped --
        # and still a list, which is public API.
        self.assertEqual(moses.NONBREAKING_PREFIXES, ["Dr", "Mr", "Prof"])
        self.assertIsInstance(moses.NONBREAKING_PREFIXES, list)

    def test_numeric_only_still_detects_the_marker(self):
        moses = MosesTokenizer()
        for text, expected in [
            ("", False),
            ("#NUMERIC_ONLY#", False),  # needs preceding whitespace
            ("a#NUMERIC_ONLY#", False),
            (" #NUMERIC_ONLY#", True),
            ("a #NUMERIC_ONLY#", True),
            ("a  #NUMERIC_ONLY#", True),
            ("a\t#NUMERIC_ONLY#", True),
            ("a\n#NUMERIC_ONLY#", True),
        ]:
            with self.subTest(text=text):
                self.assertIs(moses.has_numeric_only(text), expected)


class BenignFloodPayloads(unittest.TestCase):
    """Surfaces attacked in the same sweep and found linear. Kept anyway.

    None of these is a finding today. They are here because each drives a
    different loop -- detokenisation, XML escaping, detruecasing, punctuation
    normalisation -- that no regex-shaped scan would connect to a payload at
    all, and because the two real DoS bugs in this library were exactly that
    kind of loop. Recording only the hits would leave nothing to notice when
    one of these stops being linear.
    """

    def flood(self, func, payload):
        return elapsed(func, payload)

    def test_detokenizer_floods(self):
        detok = MosesDetokenizer(lang="en")
        for name, tokens in [
            ("quotes", ['"'] * 20000),
            ("open parens", ["("] * 20000),
            ("alternating", ['"', "'"] * 10000),
            ("cjk run", ["我"] * 20000),
            ("dots", ["."] * 20000),
        ]:
            with self.subTest(payload=name):
                self.assertLess(self.flood(detok.detokenize, tokens), BUDGET_SECONDS)

    def test_xml_escaping_floods(self):
        tok = MosesTokenizer(lang="en")
        detok = MosesDetokenizer(lang="en")
        for name, func, payload in [
            ("escape &", tok.escape_xml, "&" * 200000),
            ("unescape &amp;", detok.unescape_xml, "&amp;" * 100000),
            # Deep nesting: the shape an entity-expansion attack would take, if
            # this were an entity parser. It is a flat string replace, so it is
            # linear -- pinned in case that ever changes.
            ("unescape nested", detok.unescape_xml, "&" + "amp;" * 100000),
        ]:
            with self.subTest(payload=name):
                self.assertLess(self.flood(func, payload), BUDGET_SECONDS)

    def test_detruecaser_flood(self):
        self.assertLess(
            self.flood(MosesDetruecaser().detruecase, "a " * 100000), BUDGET_SECONDS
        )

    def test_normalizer_shape_floods(self):
        norm = MosesPunctNormalizer()
        for name, payload in [
            ("nested brackets", "(" * 20000 + ")" * 20000),
            ("mixed quotes", "„“”\xab\xbb" * 20000),
            ("numbers and commas", "1," * 50000),
            ("newlines", "\n" * 100000),
        ]:
            with self.subTest(payload=name):
                self.assertLess(self.flood(norm.normalize, payload), BUDGET_SECONDS)

    def test_tokenizer_shape_floods(self):
        tok = MosesTokenizer(lang="en")
        for name, payload in [
            ("tabs", "\t" * 200000),
            ("at signs", "a@" * 20000),
            ("slashes", "/" * 20000),
            ("ampersands", "&" * 20000),
        ]:
            with self.subTest(payload=name):
                self.assertLess(self.flood(tok.tokenize, payload), BUDGET_SECONDS)


class ProtectedTokenIntegrity(unittest.TestCase):
    """The placeholder used to protect spans must not be forgeable or overrun.

    ``protected_patterns`` replaces each matched span with a placeholder, runs
    the tokenizer, then substitutes the spans back with a blind
    ``str.replace``. Two things follow from that, and both were live:

    * the placeholder count was bounded only by ``assert``, which ``python -O``
      removes -- past 1000 the fixed-width counter overran and spans were
      silently lost;
    * the placeholder stem was the constant ``THISISPROTECTED``, and the input
      was never checked for it, so text containing that literal had it
      rewritten into whatever span shared its index.
    """

    PATTERNS = MosesTokenizer.BASIC_PROTECTED_PATTERNS
    FORGERIES = [
        "THISISPROTECTED000",
        "THISISPROTECTED",
        "THISISPROTECTEDX000",
        "THISISPROTECTEDXXXX000",
        "THISISPROTECTED000 THISISPROTECTEDX001",
    ]

    def test_sanity_urls_are_actually_protected(self):
        # Guards the tests below: BASIC_PROTECTED_PATTERN_5 needs a path
        # segment, so a bare 'http://a.com' is NOT protected and would make
        # every assertion here vacuous.
        moses = MosesTokenizer()
        self.assertIn(
            "http://good.com/p",
            moses.tokenize("x http://good.com/p y", protected_patterns=self.PATTERNS),
        )

    def test_placeholder_in_input_is_not_rewritten(self):
        moses = MosesTokenizer()
        for forgery in self.FORGERIES:
            with self.subTest(forgery=forgery):
                out = " ".join(
                    moses.tokenize(
                        "http://a.com/p %s http://b.com/p" % forgery,
                        protected_patterns=self.PATTERNS,
                    )
                )
                self.assertIn(forgery, out)
                # The protected spans must appear once each -- never relocated
                # or duplicated into the position the forgery occupied.
                self.assertEqual(out.count("http://a.com/p"), 1)
                self.assertEqual(out.count("http://b.com/p"), 1)

    def test_marker_escapes_past_any_run_in_the_input(self):
        moses = MosesTokenizer()
        stem = MosesTokenizer.PROTECT_MARKER
        for text in ("", "no marker here", stem, stem + "XXX", stem + "X" * 40):
            with self.subTest(text=text):
                self.assertNotIn(moses.unused_protect_marker(text), text)

    def test_too_many_protected_tokens_raises(self):
        # Must be a real exception, not an assert: under `python -O` an assert
        # is compiled away and the overrun happens silently.
        moses = MosesTokenizer()
        limit = MosesTokenizer.MAX_PROTECTED_TOKENS
        text = " ".join("http://e%d.com/p" % i for i in range(limit + 1))
        with self.assertRaises(ValueError):
            moses.tokenize(text, protected_patterns=self.PATTERNS)

    def test_at_the_limit_every_span_survives(self):
        moses = MosesTokenizer()
        urls = ["http://e%d.com/p" % i for i in range(MosesTokenizer.MAX_PROTECTED_TOKENS)]
        out = set(moses.tokenize(" ".join(urls), protected_patterns=self.PATTERNS))
        self.assertEqual([url for url in urls if url not in out], [])

    def test_bound_holds_without_assertions(self):
        # Re-run the two assertions above in a child interpreter with -O, which
        # is what a slim container image does by default.
        import subprocess
        import sys

        program = (
            "from sacremoses import MosesTokenizer as T\n"
            "m = T(); P = T.BASIC_PROTECTED_PATTERNS\n"
            "assert not __debug__\n"
            "n = T.MAX_PROTECTED_TOKENS\n"
            "urls = ['http://e%d.com/p' % i for i in range(n)]\n"
            "out = set(m.tokenize(' '.join(urls), protected_patterns=P))\n"
            "assert all(u in out for u in urls), 'spans lost at the limit'\n"
            "try:\n"
            "    m.tokenize(' '.join(urls + ['http://over.com/p']), protected_patterns=P)\n"
            "except ValueError:\n"
            "    print('bounded')\n"
            "else:\n"
            "    raise SystemExit('overran the placeholder space under -O')\n"
        )
        result = subprocess.run(
            [sys.executable, "-O", "-c", program], capture_output=True, text=True
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("bounded", result.stdout)


class UpstreamRegressions(unittest.TestCase):
    """Correctness bugs found in the same sweep. Not attacks, but silent."""

    def test_is_cjk_includes_range_boundaries(self):
        # The comparison was exclusive on both ends, dropping the first and
        # last codepoint of all 11 ranges -- 22 characters, among them U+AC00,
        # the most common Korean syllable.
        from sacremoses.util import CJKChars, is_cjk

        for start, end in CJKChars().ranges:
            with self.subTest(start=hex(start), end=hex(end)):
                self.assertTrue(is_cjk(chr(start)))
                self.assertTrue(is_cjk(chr(end)))
        self.assertTrue(is_cjk("가"))
        # Still exclusive outside the ranges.
        for start, end in CJKChars().ranges:
            with self.subTest(below=hex(start)):
                self.assertFalse(is_cjk(chr(start - 1)))

    def test_perl_parity_does_not_leak_between_instances(self):
        # `perl_parity=True` assigned into the class-level substitution lists,
        # so constructing one parity normalizer rewrote the defaults for every
        # other normalizer in the process.
        before = list(MosesPunctNormalizer.NORMALIZE_UNICODE)
        MosesPunctNormalizer(perl_parity=True)
        self.assertEqual(list(MosesPunctNormalizer.NORMALIZE_UNICODE), before)
        self.assertEqual(
            MosesPunctNormalizer().normalize("He said 'hi'"), "He said 'hi'"
        )


class BehaviourUnchanged(unittest.TestCase):
    """The hardening must not change what the library produces."""

    def test_tokenize_roundtrip(self):
        moses = MosesTokenizer(lang="en")
        detok = MosesDetokenizer(lang="en")
        text = "This ain't funny. It's actually hillarious, yet double Ls. | [] & You're gonna shake it off? Don't?"
        self.assertEqual(detok.detokenize(moses.tokenize(text)), text)

    def test_known_tokenization(self):
        moses = MosesTokenizer(lang="en")
        self.assertEqual(
            moses.tokenize("This, is a sentence with weird\xbb symbols… appearing everywhere\xbf"),
            "This , is a sentence with weird \xbb symbols … appearing everywhere \xbf".split(),
        )

    def test_normalizer_unchanged(self):
        normalizer = MosesPunctNormalizer()
        self.assertEqual(normalizer.normalize("The  quick  brown"), "The quick brown")

    def test_all_languages_still_load(self):
        prefixes = NonbreakingPrefixes()
        for lang in sorted(set(prefixes.available_langs.values())):
            with self.subTest(lang=lang):
                self.assertTrue(list(prefixes.words(lang)))


if __name__ == "__main__":
    unittest.main()
