#!/usr/bin/env python3
"""Regenerate the code-defined data modules from the .txt sources.

sacremoses ships its Unicode character classes and nonbreaking prefixes as code
rather than as package data, so nothing is read from disk at run time. This
script converts ``sacremoses/data/`` into those modules and is NOT part of the
distributed package -- run it only when the upstream .txt data changes.

    python tools/generate_data_modules.py

The character classes are emitted verbatim, in file order, including any
trailing newline: ``Perluniprops.chars()`` historically yielded every character
of the file, and the order matters because these strings are interpolated into
regex character classes, where moving a '-' would silently create a range.
"""

import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "sacremoses", "data")

HEADER = '''"""Auto-generated by tools/generate_data_modules.py -- do not edit by hand.

Generated from {source}. Kept as code so that sacremoses reads no data files at
run time.
"""

'''


def emit_perluniprops():
    src = os.path.join(DATA, "perluniprops")
    entries = []
    for name in sorted(os.listdir(src)):
        if not name.endswith(".txt"):
            continue
        with open(os.path.join(src, name), encoding="utf-8") as fin:
            entries.append((name[: -len(".txt")], fin.read()))
    out = [HEADER.format(source="sacremoses/data/perluniprops/*.txt")]
    out.append("#: Category name -> the exact characters of that category.\n")
    out.append("PERLUNIPROPS = {\n")
    for category, text in entries:
        out.append("    %r: %r,\n" % (category, text))
    out.append("}\n")
    return "".join(out), len(entries)


def emit_nonbreaking_prefixes():
    src = os.path.join(DATA, "nonbreaking_prefixes")
    entries = []
    for name in sorted(os.listdir(src)):
        path = os.path.join(src, name)
        if not os.path.isfile(path) or name.startswith("."):
            continue
        with open(path, encoding="utf-8") as fin:
            entries.append((name, fin.read()))
    out = [HEADER.format(source="sacremoses/data/nonbreaking_prefixes/*")]
    out.append("#: File name -> the exact contents of that prefix file.\n")
    out.append("NONBREAKING_PREFIXES = {\n")
    for name, text in entries:
        out.append("    %r: %r,\n" % (name, text))
    out.append("}\n")
    return "".join(out), len(entries)


def main():
    for filename, emit in (
        ("_data_perluniprops.py", emit_perluniprops),
        ("_data_nonbreaking_prefixes.py", emit_nonbreaking_prefixes),
    ):
        source, count = emit()
        target = os.path.join(HERE, "sacremoses", filename)
        with open(target, "w", encoding="utf-8") as fout:
            fout.write(source)
        print(f"wrote {filename}: {count} entries, {len(source):,} bytes")


if __name__ == "__main__":
    main()
